# Generated by Django 5.0.6 on 2024-07-08 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packagename', models.CharField(max_length=100)),
                ('placename', models.CharField(max_length=100)),
                ('movefrom', models.CharField(max_length=100)),
                ('tofrom', models.CharField(max_length=100)),
                ('movedate', models.DateField()),
                ('todate', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('totaltourist', models.IntegerField()),
                ('Available_slot', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='package_images/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Tourist', 'Tourist'), ('Agent', 'Agent')], max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.PositiveIntegerField()),
                ('address', models.TextField()),
                ('age', models.BigIntegerField(null=True)),
                ('password', models.CharField(max_length=20)),
                ('profile_image', models.ImageField(default='userprofile.png', upload_to='user_profile/')),
                ('disignation', models.CharField(max_length=50, null=True)),
                ('facebooklink', models.URLField(null=True)),
                ('instagram', models.URLField(null=True)),
                ('twiter', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DayDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('description', models.TextField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.package')),
            ],
        ),
        migrations.CreateModel(
            name='PackageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='package_images/')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.package')),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packagename', models.CharField(max_length=50)),
                ('packageprice', models.PositiveIntegerField()),
                ('username', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('contact', models.PositiveBigIntegerField()),
                ('address', models.TextField()),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
